### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by diegoorellanaga** [ellisdg/3DUnetCNN#113]
I have been checking this project code and I can't find the code that normalizes the data. I know that the preprocessed data is not normalized but the .h5 data is. If you can point out the code that does that I would really appreciate. Thank you.

**Comment by ellisdg** [comment]
[Here you go!](https://github.com/ellisdg/3DUnetCNN/blob/master/unet3d/normalize.py#L72)

**Comment by ellisdg** [comment]
As a side note, the code currently normalizes based on the mean and standard deviation (for a given modality) across the entire dataset. I'm [planning on changing it](https://github.com/ellisdg/3DUnetCNN/blob/image_files/unet3d/normalize.py#L72) so that the data will be normalized on a per image basis.

**Comment by diegoorellanaga** [comment]
Thank you!
