### ISSUE TITLE
Questions about affine

### ISSUE THREAD

**Issue by connorchen** [ellisdg/3DUnetCNN#114]
hi@ellisdg
I found that affine in all train data was the same. 
[[ -1.   0.   0.  -0.]
 [  0.  -1.   0. 239.]
 [  0.   0.   1.   0.]
 [  0.   0.   0.   1.]]
In fact, I don't know what affine really does.
Now I use the new test data but affine is different from all train data.
Should i do something with the affine of the test data to makes the test result more accurate.

**Comment by ellisdg** [comment]
[This link](http://nipy.org/nibabel/coordinate_systems.html) explains coordinate systems well. I try to keep track of the affine for each image so that I can line up the resulting segmentations with the original image.

**Comment by connorchen** [comment]
thanks for your reply@ellisdg
speaking of "line up the resulting segmentations with the original image", can you share the code, i try it myself but in vain.

**Comment by ellisdg** [comment]
[Here](https://github.com/ellisdg/3DUnetCNN/blob/master/unet3d/prediction.py#L92) is the code. If you have the data and the affine matrix, you can simply create a new image. If the affine is correct, then the image will overlap with the initial image. However, this does not mean the image data matrix itself will overlap with the original image data matrix. In order to get that, you would need to resample the resulting segmentation to the original image. This can all be confusing at first, but understanding coordinate systems, affine transformations, registrations, and resampling are crucial concepts in medical image processing, so may be worth taking some time to study these topics.

**Comment by connorchen** [comment]
benefit a lot @ellisdg Thanks again
