### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by amirgholami** [ellisdg/3DUnetCNN#117]
I expected the preprocessed data to have mean of 0 and std of 1 during the normalization process. However, this seems to be not the case. For instance after calling "convert_brats_data" and examining the contents under preprocess the data does not have a zero mean. Is this expected?

Thanks,
-Amir

**Comment by ellisdg** [comment]
Normalization is done when the data is saved to an hdf5 file. See #113.

On May 30, 2018 5:52 PM, "Amir Gholami" <notifications@github.com> wrote:

I expected the preprocessed data to have mean of 0 and std of 1 during the
normalization process. However, this seems to be not the case. For instance
after calling "convert_brats_data" and examining the contents under
preprocess the data does not have a zero mean. Is this expected?

Thanks,
-Amir

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ellisdg/3DUnetCNN/issues/117>, or mute the thread

**Comment by amirgholami** [comment]
I see that makes sense. However, I wonder why you are not performing per patch normalization. Does the code support that?

**Comment by ellisdg** [comment]
Per patch normalization is a good idea, but unfortunately it is not implemented yet.

**Comment by akhanss** [comment]
Hi @ellisdg,
I am just wondering whether the feature for normalizing data on a per image basis as mentioned in #113  is implemented already. Or can anybody please help me to achieve this feature? Thank you very much. 

Best,
Azam.

**Comment by DecentMakeover** [comment]
@ellisdg Hey ill implement this , can you guide me where to start?

**Comment by ljljlj02** [comment]
I need help, too
