### ISSUE TITLE
why set the size to (144,144,144)/(128,128,128)

### ISSUE THREAD

**Issue by csuquan** [ellisdg/3DUnetCNN#159]
Can we set to different size?
could anyone tell me ?

**Comment by nysuka** [comment]
@csuquan please see https://github.com/ellisdg/3DUnetCNN/issues/15

**Comment by csuquan** [comment]
@nysuka 
@nysuka 
thank you very much.so kind of you.
I have another question.the raw iamge is (240,240,155）
but the output image is (144,144,144)
could I reshape the image to raw size?if I can ,what should I do?

**Comment by nysuka** [comment]
@csuquan do you mean restore prediction to the original dimensions?

assuming so, first save the testing MR files in the original dimensions in .h5 form, no cropping, no resizing. you can reuse `def write_data_to_file` and set crop to `False`. you can write out each case individually or lump it in one big .h5 for faster processing.

then modify the prediction scenario, additionally feed in the original sized testing .h5 into `def run_validation_case`, use nilearn's resample_to_img to resample the prediction (144,144,144) to original size (240,240,155). `org_predict_img = resample_to_img(prediction_image, original, interpolation="nearest")`

**Comment by csuquan** [comment]
@nysuka 
I failed to resize the image .
I change the code in 145line of unet3d.prediction.py
`original = nib.load('/media/cb201/disk2/quan/3DUnetCNN-master/brats/data/brats18validation/HGG/Brats18_WashU_W047_1/t1ce.nii.gz')
        org_predict_img = resample_to_img(prediction_image, original, interpolation="nearest")
        #prediction_image.to_filename(os.path.join(output_dir, "prediction.nii.gz"))
        org_predict_img.to_filename(os.path.join(output_dir, "prediction.nii.gz"))`


But the result is bad. the result is abnormal.

**Comment by chengjianhong** [comment]
@ellisdg @nysuka Hi, There is a strange phenomenon. When I  try to reshape the image to raw size using `resample_to_img` function, it works for the Brats2017 data, but it doesn't work for the Brats 2018 data.

**Comment by ellisdg** [comment]
@chengjianhong what does the prediction image look like before resampling?

**Comment by chengjianhong** [comment]
@ellisdg It looks like this.
[prediction.nii.gz](https://github.com/ellisdg/3DUnetCNN/files/2889758/prediction.nii.gz)

**Comment by ellisdg** [comment]
So this is where the original T1 volume is located in 3D space:
![t1](https://user-images.githubusercontent.com/8558995/53178822-3884e980-35b8-11e9-8555-f0286ff5e025.png)
And this is where your prediction volume is located in 3D space:
![tumor](https://user-images.githubusercontent.com/8558995/53178858-43d81500-35b8-11e9-9426-344014ca6555.png)

As you can see, they are not aligned. So when you resample the prediction back into the original space, you end up getting a blank image because outside the prediction volume, the resampling assumes that everything is zero.

There is probably an error in the code in how the affine of the images are computed before being saved in the h5 file. Or it could be in how the affine of the prediction image is computed. I'll take a look at it in the next few days and see if I can reproduce and fix the issue. You could also resample all of the 2018 images into RAS orientation and then save those images (make sure to not overwrite the original ones). This can be done in nilearn:

```
from nilearn.image import reorder_img

ras_image = reorder_img(image)
```

You would then need to create a new h5 file with the reordered data and then make your predictions from the new h5 file.

Volume location and orientation in 3D is tricky, but if you want to learn more, you can check out this link:
http://nipy.org/nibabel/coordinate_systems.html

**Comment by chengjianhong** [comment]
@ellisdg Thank you so much. Can you tell me what is your tools to view the prediction volume in 3D space?

**Comment by ellisdg** [comment]
3D Slicer: https://www.slicer.org/

It's my favorite tool for visualizing medical imaging data.

**Comment by chengjianhong** [comment]
@ellisdg Thanks. and I hope you can fix that issue smoothly.

**Comment by chengjianhong** [comment]
@ellisdg  Dear elisdg, does the bug be fixed about the affine of the images ?
