### ISSUE TITLE
Runtime preprocessing

### ISSUE THREAD

**Issue by akhanss** [ellisdg/3DUnetCNN#170]
Currently, we need to preprocess all the data beforehand and save to a .h5 file (config['data_file']) to feed at the network for training and validation. I am just wondering if it is possible to preprocess data one by one or number of batch_size during the training and validation. Thanks in advance.

Regards,
-Azam.

**Comment by ellisdg** [comment]
It is definitely possible to run the preprocessing steps during training. I just have it setup so that any additional processing work happens before training, so that training doesn't take as long. If you run the preprocessing every time you want to use the data, that will add a lot of overhead that you don't really need. Does that answer your quest?

**Comment by WrathofBhuvan11** [comment]
Hello I have written my own architecture based on Autoencoder Regularisation. So ,
1.) do you think this pre processing works good 
2.) Ryt now I have preprocessed data folder I'm interested in only converting this to Hdf5 (128,128,228) , which folder /piece of code would help me ?

**Comment by akhanss** [comment]
> It is definitely possible to run the preprocessing steps during training. I just have it setup so that any additional processing work happens before training, so that training doesn't take as long. If you run the preprocessing every time you want to use the data, that will add a lot of overhead that you don't really need. Does that answer your quest?

Yes, I've got your point. Thanks a lot.
