### ISSUE TITLE
How to avoid the False positives?

### ISSUE THREAD

**Issue by parvezamu** [ellisdg/3DUnetCNN#180]
Sir I have a query......during training there is no background label....during prediction you assigned the background labels to those pixels after performing the thresholding condition. May be lot of false positives in the result because during training there is no background label. If I have tried traversky loss to avoid false positives but it only avoids a very few false positives and a very few true positives will be there. So kindly suggest your valuable suggestions as I am a new in this field.

**Comment by ellisdg** [comment]
See #140 

The way it is setup now, the background is assigned when no other class prediction exceeds a threshold of 0.5. You can adjust that threshold. Making it higher (0.8) will give you fewer false positives. Making it smaller, will give you better sensitivity. You could also add a background label to the training. Then when you create the labelmap from the predictions you just select the class with the highest prediction from the model. I don't know if this is better or worse. Since the background labels are orders of magnitude more prevalent in the data, it could skew the model to predicting background more often than not. Though the averaged dice coefficient function that I implemented could help keep that from being too big of an issue.

**Comment by parvezamu** [comment]
Thanks, sir for such a useful explanation.
