### ISSUE TITLE
Why the effect is not obvious? 

### ISSUE THREAD

**Issue by chengjianhong** [ellisdg/3DUnetCNN#198]
@ellisdg Hi, thanks for your excellent works. I try to use the data augmentation(config["flip"] = True, config["permute"] = True) to train this network (isensee2017_model). I have attempted many times, but in terms of Dice, its effect is not obvious on BraTS2018 validation data. Can you gives me some advices and  help me analyze the reason ?

**Comment by ellisdg** [comment]
I believe the permutation may be too aggressive. Brain imaging data
maintains consistent orientation and the permute function messes up that
orientation. It may work better to simply have a function that mirrors the
images so that the left side is flipped to the right. That way, the brain
orientation is mostly peserved while allowing for doubling of the training
set. Off the top of my head I don't remember if I saw improvement with
permutation of the BRATS data.
