### ISSUE TITLE
Can't get good result

### ISSUE THREAD

**Issue by wangxianghan** [ellisdg/3DUnetCNN#217]
Thanks for your code. I can't get the result as good as yours. Maybe my method is not right. My ["patch_shape"] is (64, 64, 64). My 'batch_size' and 'validation_batch_size' are both 1. Other settings are the original settings. May I have your trips or advices? By the way, may I get your weights for brats2018?

**Comment by Faizad** [comment]
@wangxianghan same problem here on Brats-2018 dataset. Prediction results of whole tumor, tumor core and enhancing tumor are between 0.00 - 0.28. What should we do?

**Comment by wangxianghan** [comment]
@Faizad Thanks for your reply. I run the Isensee et al. 2017 model on Brats-2018 dataset. The result I get is always worse than the picture you show in your github. May be I did something wrong and I ask for your help. 
By the way, what does '0.00-0.28' mean? Does it mean the picture shown in the github? But the result of the picture is much better than it.
Thanks again.

**Comment by Faizad** [comment]
@wangxianghan 0.00-0.28 is the range of results i.e. minimum-maximum results. 0.00 is the worsen case while 0.28 is the best case. Remaining results are lying betwenn 0.00 to 0.28. Hence these results are not even reliable for training. 
Thanks!

**Comment by wangxianghan** [comment]
@Faizad The picutre of this method in github is much better than 0.28, does it mean we are not talking about the same method or dataset?
 By the way, what does 0.00-0.28 mean? Is that IOU value? How did you get the value, from this github code or other code you writen yourself?

**Comment by Faizad** [comment]
@wangxianghan Sure, the picture in github is far better than 0.28. The main reason is that original code is trained on Brats-2017 dataset while I trained and evalute the code on brtas-2018 dataset. That's why I am getting the results not more than 0.28.
The evaluation results stored in Prediction/ folder. You may find the evaluation results there. But it is neccessary to run the evaluate.py file given in code to get the evaluation result.

**Comment by wangxianghan** [comment]
@Faizad Sorry for the late response. You mean the picture in github is trained and tested on Brtas-2017? But they said it is on 2018 in github. Maybe I did something wrong in the training.

**Comment by Lililicg** [comment]
Hello, I can't download the dataset and the registration has not been passed. Could you please send your dataset to me? Thank you very much.

**Comment by Faizad** [comment]
@Lililicg https://www.med.upenn.edu/sbia/brats2018/registration.html
Sorry I can't send you the data, but you can easily download data from the mentioned site.
Thanks!

**Comment by Lililicg** [comment]
我注册一直没通过 一直处于审核状态&nbsp; 能麻烦你发一下吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Faizad Ullah"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月10日(星期四) 中午1:22
收件人:&nbsp;"ellisdg/3DUnetCNN"<3DUnetCNN@noreply.github.com&gt;;
抄送:&nbsp;"416580793"<416580793@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ellisdg/3DUnetCNN] Can't get good result (#217)




@Lililicg https://www.med.upenn.edu/sbia/brats2018/registration.html
 Sorry I can't send you the data, but you can easily download data from the mentioned site.
 Thanks!

**Comment by parvezamu** [comment]
I have the training dataset..........if you are from China.....you can share your qq number...I will send you in two parts because the limit is less than 2GB

**Comment by parvezamu** [comment]
I have the training dataset..........if you are from China.....you can share your qq number...I will send you in two parts because the limit is less than 2GB

**Comment by Lililicg** [comment]
416580793 谢谢Thanks♪(･ω･)ﾉ




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"PARVEZ AHMAD"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月10日(星期四) 下午3:09
收件人:&nbsp;"ellisdg/3DUnetCNN"<3DUnetCNN@noreply.github.com&gt;;
抄送:&nbsp;"416580793"<416580793@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ellisdg/3DUnetCNN] Can't get good result (#217)




I have the training dataset..........if you are from China.....you can share your qq number...I will send you in two parts because the limit is less than 2GB

**Comment by Lililicg** [comment]
你这边有把数据存在网盘里吗 如果有存的话 可以建立一个网盘链接我自行转存吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"PARVEZ AHMAD"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月10日(星期四) 下午3:09
收件人:&nbsp;"ellisdg/3DUnetCNN"<3DUnetCNN@noreply.github.com&gt;;
抄送:&nbsp;"416580793"<416580793@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ellisdg/3DUnetCNN] Can't get good result (#217)




I have the training dataset..........if you are from China.....you can share your qq number...I will send you in two parts because the limit is less than 2GB

**Comment by tecWang** [comment]
> I have the training dataset..........if you are from China.....you can share your qq number...I will send you in two parts because the limit is less than 2GB

I have applied for the BraTS2018 for five days. But they still haven't passed my application. If you have the training data of it, could you share it with me? The dataset will be only used for research. And my email is 790563432w@gmail.com. Thank you!
