### ISSUE TITLE
Query about the preprocessing

### ISSUE THREAD

**Issue by namco1992** [ellisdg/3DUnetCNN#24]
Hi ellisdg,
I am a rookie in deep learning, especially in 3D neural networks. I wonder why you convert the .mha to .nii, and then write the .nii into the hdf5 file. What are the purposes of these preprocessing steps? I read part of your source code and I think it's a wonderful learning material for me, I truly hope to learn about more details about the implementation.

**Comment by ellisdg** [comment]
That's a good question! It is a bit redundant to save the data 3 times. I convert them to a .nii during preprocessing because [.nii files](https://nifti.nimh.nih.gov/) can be read by [nibabel](http://nipy.org/nibabel/). I could have just went ahead and saved them to a hdf5 file during preprocessing, but this code was written in stages, and the preprocessing part was written before I realized I wanted to use hdf5. I chose to use an hdf5 file later, as this allows for the data to be quickly accessed without storing all of the data in memory.

**Comment by namco1992** [comment]
Thank you for the response. According to your explanation, you convert .mha to .nii because you want to use nibabel to perform some transformations, and you save all the data as a hdf5 file because of the efficiency of data access. Is my understanding right?

**Comment by ellisdg** [comment]
That's correct!
