### ISSUE TITLE
convert_brats_data NotImplementedError

### ISSUE THREAD

**Issue by navidnadery** [ellisdg/3DUnetCNN#29]
Hi there,
when I try to run convert_brats_data, I run to an error and I don't know how to solve it. I've searched but I could not find any solution.
Here is error:
![screenshot from 2017-08-07 13 48 32](https://user-images.githubusercontent.com/12444857/29020433-3b6f23ba-7b77-11e7-943d-6db7f0c06d10.png)

thanks regards.

**Comment by ellisdg** [comment]
As the error points out, something is going wrong at line 62 of preprocess.py. SimpleITK is complaining because it doesn't recognize the input that is being passed to sitk.ReadImage on that line. The input ```in_file``` should be a string containing the location of an image file on disk. My guess is that something is wrong with that variable. Can you try printing ```in_file``` at that line or better yet running a debugger to find out?

**Comment by navidnadery** [comment]
Hi @ellisdg and thanks for your response.
Yeah I checked the path and sometimes it will be unicode, so I convert path to string and it continues.
But I ran to another problem, I see so many problems step by step and I solve them. Is there any problem in Brats 2015 Data set? Here is my new error:
![image](https://user-images.githubusercontent.com/12444857/29076865-01c32526-7c6c-11e7-9484-013fcaedc9da.png)

**Comment by navidnadery** [comment]
Thanks for your help.
The problem is that some PATHs are known as Unicode and just need a conversion to string.

**Comment by ellisdg** [comment]
Thanks for the update. Are you using Python 2?

**Comment by navidnadery** [comment]
No problem, sorry for delay.
I am using python 2.7

**Comment by iamyourdaddy** [comment]
have you ever met the problem Interface N4BiasFieldCorrection failed to run.@navidnadery

**Comment by navidnadery** [comment]
Yeah, It occures in two ways:
The first one is when you have not added ANTs PATH to your system PATH.
The second one is because of address type and you should convert Unucode addressess to String.
Could you post whole errore or take a snapshot?

**Comment by iamyourdaddy** [comment]
very happy you replied me so soon 

 i have add the ANTs path to the system path i will make sure about it again, but i don't know how to convert unicode address to string ......i will try to solve this 

the problem is in this url:   https://github.com/ellisdg/3DUnetCNN/issues/32
  any more suggestion?

**Comment by iamyourdaddy** [comment]
@navidnadery

**Comment by ianyourdaddy** [comment]
very happy you replied me so soon

i have add the ANTs path to the system path i will make sure about it again, but i don't know how to convert unicode address to string ......i will try to solve this

the problem is in this url: #32
any more suggestion?

**Comment by ianyourdaddy** [comment]
@navidnadery

**Comment by navidnadery** [comment]
It seems that you are running in windows, I am using Ubuntu Linux.
But I think there is not much difference, open file SimpleITK.py go to line 8332 and befor return command write this line:

args = [s.encode('utf8') if type(s)==unicode else s for s in args]

**Comment by navidnadery** [comment]
or you can print the Path came in using this command:
print(args)

You can see and find the problem and solve it.

**Comment by ianyourdaddy** [comment]
thanks for the reply, I will check the circumstance you tell. i have found that simpleitk can also solve this problem. and  i will try on the linux platform. maybe tomorrow i can found where the bug is.

maybe we can communicate on medical image process~


thanks

**Comment by ianyourdaddy** [comment]
maybe we can add friend in wechat. do you know about wechat? its a very famous app for communication in china

**Comment by ianyourdaddy** [comment]
@navidnadery

**Comment by navidnadery** [comment]
Wechat is good but I live in Iran and the government had filtered Wechat, so we can not connect.
But Viber and Telegram and Whatsapp is OK.

**Comment by ianyourdaddy** [comment]
@navidnadery hi i have registered a whatsapp account ,you can add my account through numbers: +8615910913169

**Comment by ellisdg** [comment]
@ianyourdaddy, I use Mac and Ubuntu, so I haven't ever installed ANTs on Windows, but [this link](https://github.com/stnava/ANTsR/wiki/Installing-ANTsR-in-Windows-10-(along-with-FSL,-Rstudio,-Freesurfer,-etc).) describes how to install ANTsR (which is ANTs for the R statistical tool/language) along with some other packages. Those instructions could be adapted to install just plain ANTs. It looks like there is a [Linux interface that you can use on Windows] that will allow you to do this.( https://msdn.microsoft.com/en-us/commandline/wsl/install_guide).

As for the original @navidnadery's Unicode issue, that problem might be isolated to Python 2. I have been using Python 3 for this project, so that might be why I haven't encountered this issue.

**Comment by ianyourdaddy** [comment]
thanks for the reply, i have try to run this code in linux and it works, maybe the question is that the ANTs is not working in windows. and i also try to use SIMPLEITK lib for N4biascorrection, but it still not work...opps~

maybe the preprocess can only be used in linux.

thanks  anyway

by the way you are also focus on medical image process?

@ellisdg

**Comment by ellisdg** [comment]
Yes, medical image processing is my job!

**Comment by nouranik** [comment]
> Wechat is good but I live in Iran and the government had filtered Wechat, so we can not connect.
> But Viber and Telegram and Whatsapp is OK.

Salam Navid,
I started working with this code, I am new in python and have a few questions, is it possible to contact you? thanks.
