### ISSUE TITLE
Can't run the program! 

### ISSUE THREAD

**Issue by Micheal1989** [ellisdg/3DUnetCNN#344]
Hi, ellisdg:
    When I run the program, one problem has occured which  cost my whole day to try solve . So,I wish you can help me solve the problem and run the program .

Here is error:
![git_issue](https://github.com/user-attachments/assets/66a6542f-3953-4cb7-a94b-3c65c8743cf3)

[my_requirements.txt](https://github.com/user-attachments/files/16311491/my_requirements.txt)

**Comment by ellisdg** [comment]
This looks like an issue with your configuration file. Are you running the train.py script?

**Comment by ellisdg** [comment]
More specifically, the program can't find the file shown in your screenshot. Does that file exist from the directory in which you are running the script? Assuming you have the downloaded the BraTS dataset, the most likely culprits is that the directory within which you are running the script does not have the "BraTS2020_TrainingData" in it. You need to either change to the directory that does have that folder or you can update the configuration file to use absolute rather than relative path names.

**Comment by Micheal1989** [comment]
Yes,I make a mistake that I put the two data_files in the folder brats2020. I should have put them in the folder-3DUnetCNN or change create_config_lowmen.ipynb.
Thank your advice and  gratitude for your work。
