### ISSUE TITLE
Convert to Tensorflow

### ISSUE THREAD

**Issue by leacornelio** [ellisdg/3DUnetCNN#45]
do you have any suggestions on how to convert this Keras model to a Tensorflow model?

**Comment by mingrui** [comment]
keras is a wrapper for tensorflow, turn on tensorflow as backend for keras and start from there?

**Comment by jamespeterthornton** [comment]
The most noteworthy change is to switch the axis of concatenation to the last channel instead of the first. This is because Theano is channels_first but Tensorflow is channels_last. E.g. change 'concatenate([up5, conv3], axis=1)' to 'concatenate([up5, conv3], axis=4)'. Otherwise, things can generally stay the same.

**Comment by Zerseu** [comment]
Could you please elaborate more on the changes needed to use TensorFlow as backend?
I have applied the fix above, setting axis=4, but am getting this message when trying to run:

ValueError: Error when checking input: expected input_1 to have shape (None, 64, 64, 32, 1) but got array with shape (1, 1, 64, 64, 32)

**Comment by Zerseu** [comment]
I think it's from "data.py", function "add_data_to_storage". Any help would be appreciated.

**Comment by ellisdg** [comment]
To use Tensorflow as a backend, you don't need to change any of the code. Simply follow the instructions listed in the Keras [backend documentation](https://keras.io/backend/).

**Comment by mingrui** [comment]
Tested with 

`KERAS_BACKEND=tensorflow python train.py`

Works well
