### ISSUE TITLE
nibabel.filebasedimages.ImageFileError

### ISSUE THREAD

**Issue by build2create** [ellisdg/3DUnetCNN#5]
I am also using BRATS dataset containing the images in mha format. Will that not work? I saw in your readme that you have used BRATS 2015 dataset. The folders inside my ./data for a particular patient looks something like this
![screenshot from 2017-04-07 15 16 09](https://cloud.githubusercontent.com/assets/25721143/24795143/ede99610-1ba5-11e7-8d2c-89b75c73e6cf.png)
The content inside the folder lloks like this
![screenshot from 2017-04-07 15 24 15](https://cloud.githubusercontent.com/assets/25721143/24795241/49673eca-1ba6-11e7-8627-5a55c8d06cc3.png)

I even tried to zip  the mha file and then give it as input but  no help.
I tried this in `normalize.py`
`background_path = os.path.join(subject_folder, subject_folder.split("/")[-1]+str(".mha.gz"))`

Please let  me know what is the correct way to give input of images. Also what is foreground and background in your context? I mean we are using 4 modalities T1,T2, T1c and FLAIR and of course ground truth. I cannot understand background or  foreground in this  context. 

PS I am using latest code updated 13 hours ago

**Comment by build2create** [comment]
Please give details about your input file format. I am also using BRATS but there are images of extension `mha`. While you are giving input as `.ni.gz` image. I have also tried converting `mha to nii ` but not much help. Getting value error then. Please help

**Comment by build2create** [comment]
Please reply

**Comment by ellisdg** [comment]
Hey @build2create, I just uploaded [preprocess.py](https://github.com/ellisdg/3DUnetCNN/commit/e6a8a482f15803b24fc4bda6e2a0bd001ca77c87) with my preprocessing methods in it.

```
from preprocess import convert_brats_data
from config import config

print(config["data_dir"])  # shows where the data will be converted to. Change this in the source code if you want a different directory
convert_brats_data("/path/to/BRATS/BRATS2015_Training",  config["data_dir"])
```

You need to have [N4BiasFieldCorrection from ANTs](https://sourceforge.net/projects/advants/) installed in order to make it work.

As a general note, the '.mha' files can be converted using SimpleITK.

**Comment by ellisdg** [comment]
@build2create I am using background to denote the image pixels that are not a part of the brain. The foreground is the opposite of the background. I save these images because the original files have a lot of extra padding around them. Reducing this extra padding makes running them through CNN slightly less memory intensive.

**Comment by build2create** [comment]
Done. That worked like a charm. Thanks. But now I am getting a new error in line 64 of `data.py`  `data_list.append(read_image(os.path.join(folder, modality + ".nii.gz"), image_shape=image_shape, crop=crop)).get_data()` saying` AttributeError: 'NoneType' object has no attribute 'get_data'`

**Comment by build2create** [comment]
@ellisdg  Please reply

**Comment by ellisdg** [comment]
I won't be able to look into it until tomorrow or Monday. If you figure out
what is going wrong before then, could you submit a pull request that fixes
the issue?

**Comment by build2create** [comment]
@ellisdg Did you figure out the problem? I am still stuck.

**Comment by ellisdg** [comment]
@build2create I believe that issue should be fixed now.

**Comment by build2create** [comment]
Thanks a lot it worked!
