### ISSUE TITLE
No module named brats.train 

### ISSUE THREAD

**Issue by kdk411** [ellisdg/3DUnetCNN#83]
Hello,

I am trying to replicate what is written in the README but I am stuck on step 5 with the complaint as the following
```
from preprocess import convert_brats_data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "preprocess.py", line 15, in <module>
    from brats.train import config
ImportError: No module named brats.train
```
To be fair, I haven't yet done ccmake for ANTs... simply because I am using a server and don't have a privilege to do so. 

So the question is, is this error coming from the fact that I haven't installed ANTs or i need to install some module called brats (or brats.train)?

**Comment by ellisdg** [comment]
This is just importing code from the file 'brats/train.py'. If you are
getting this error you are probably in a different directory or you didn't
add the project directory to the PYTHONPATH variable.

On Feb 8, 2018 5:50 PM, "Donnie Kim" <notifications@github.com> wrote:

Hello,

I am trying to replicate what is written in the README but I am stuck on
step 5 with the complaint as the following

from preprocess import convert_brats_data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "preprocess.py", line 15, in <module>
    from brats.train import config
ImportError: No module named brats.train

To be fair, I haven't yet done ccmake for ANTs... simply because I am using
a server and don't have a privilege to do so.

So the question is, is this error coming from the fact that I haven't
installed ANTs or i need to install some module called brats (or
brats.train)?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ellisdg/3DUnetCNN/issues/83>, or mute the thread

**Comment by kdk411** [comment]
Hi,

My PYTHONPATH is set up as the following:

```
q1prphtcs18:/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/BRATS/3DUnetCNN/brats:145 % echo $PYTHONPATH
/rsrch1/bcb/Imaging-Genomics_SIBL/DONNIE_KIM/Brachy_deep_learning/BRATS/3DUnetCNN:/software/x86_64/python/2.7.13/lib/python2.7/site-packages
```

I can see that 3DUnetCNN is added to the pythonpath. Is this the directory I need to add? on Step 4, it says, 'Add the repository directory to the PYTONPATH system variable'.

And I assumed the repository directory is the 3DUnetCNN

**Comment by ellisdg** [comment]
I was replicate this problem in Python 2.7. Is that what you are using?

**Comment by kdk411** [comment]
Yes, I am using Python 2.7.13... Should I use python 3.x?

**Comment by kdk411** [comment]
Hello again,

Can you please verify which python version to use? is it the problem of 2.7 or something else...? If 2.7, should I use python3.x?

**Comment by ellisdg** [comment]
I use Python 3.6. I also updated the code so that the preprocessing should work with Python 2.
