### ISSUE TITLE
What is the purpose of bias_correction in converting brats data?

### ISSUE THREAD

**Issue by MissLikeWind** [ellisdg/3DUnetCNN#90]

**Comment by ellisdg** [comment]
MR scans often display intensity non-uniformities due to variations in the magnetic field. So, one part of an image might appear lighter or darker when visualized, solely because of variations in the magnetic field. The map of these variations is called the [bias field](http://brainsuite.org/processing/surfaceextraction/bfc/). The bias field can cause problems for a classifier as the variations in signal intensity are not due to any anatomical differences. [ANTs N4 Bias Field Correction](https://www.ncbi.nlm.nih.gov/pubmed/?term=%22N4%22+AND+%22Tustison+N4ITK%22) attempts to correct the bias field by extracting it from the image.
![bias field visualization](http://www.brainvoyager.com/bvqx/doc/UsersGuide/Segmentation/Images/IIHC_Explanation_sm.png)

**Comment by MissLikeWind** [comment]
Thank you very much!
